### ISSUE TITLE
EOF error

### ISSUE THREAD

**Issue by weinstockj** [auerlab/vcf-split#4]
Hi Jason,

Some of the BCFs have completed. Some failed with "EOF reached unexpectedly" - they all failed with this same error message. Have you observed this with the same BCFs?

Edit: To add a bit more info, chroms: 10, 11, 12, 13, 18, 19, 20, 21, 3, and 7 failed. Looks like they did create some of the single sample VCFs before exit code 1. 

Thanks,
Josh

**Comment by outpaddling** [comment]
Yes, I pushed a workaround for this a few days back.

I think what's happening is a missing newline on the last line of input in some cases.  I don't think it's a problem based on the fact that output quantities are about what we would expect, but I plan to investigate further to verify exactly what's happening.

**Comment by outpaddling** [comment]
Fixed in ba9f9239.  Thanks!
