### ISSUE TITLE
problems with installation

### ISSUE THREAD

**Issue by pauline-ng** [auerlab/vcf-split#5]
Hi,

I don't have root access so I need to install vcf-split locally. I cloned libextend, libbiolibc, and vcf-split and ran 

`make LOCALBASE=$my_home_dir/local clean depend install`

for all those repos. When I run vcf-split, I get the error:
 
` bin/vcf-split: error while loading shared libraries: libbiolibc.so.2: cannot open shared object file: No such file or directory`
 
My directory structure is:
```
local/bin:
vcf-split

local/include:
biolibc  xtend

local/lib:
libbiolibc.a   libbiolibc.so.2    libxtend.a   libxtend.so.2
libbiolibc.so  libbiolibc.so.2.0  libxtend.so  libxtend.so.2.0

local/man:
man1  man3
 
```

It's been a long time since I wrote C, any advice would be appreciated. Thanks!

Pauline

**Comment by outpaddling** [comment]
Hello Pauline,

What operating system are you using?  You can just post the output of "uname -a" so we have the full details.

Have you tried auto-pkgsrc-setup?

Cheers,

     Jason

**Comment by outpaddling** [comment]
Feedback timeout.  Feel free to reopen if this is still a problem.
