### ISSUE TITLE
problems with installation 

### ISSUE THREAD

**Issue by xiaoyaohao** [auerlab/vcf-split#6]
Hello, Jason

I have the same situation as Pauline, #5 . When I run vcf-split, I get the same error:

`./local/bin/vcf-split: error while loading shared libraries: libbiolibc.so.2: cannot open shared object file: No such file or directory`

My directory structure is the same as Pauline, the system information is:

`Linux submit2.sibcb.ac.cn 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Thanks,
JIahao

**Comment by outpaddling** [comment]
Ni hao Jianhao,

I'm guessing that you just want to run it and not modify the code?  Did you try installing via pkgsrc as described in the README?  The auto-install-pkgsrc script generally takes about 10 minutes.  Then add the pkgsrc bin directory to your PATH using the init scripts or modules installed under pkgsrc-prefix/etc by auto-pkgsrc-setup, e.g. for a Bourne-family shell (bash, dash, ksh, zsh, etc.):

```
source ~/Pkgsrc/pkg/etc/pkgsrc.sh
```
To install vcf-split:
```
cd ~/Pkgsrc/pkgsrc/biology/vcf-split
sbmake install
```
There are currently about 16,000 other packages that can be installed just as easily, including 74 in the biology category:

```
NetBSD netbsd9.acadix  bacon ~ 1006: (pkgsrc): ls ~/Pkgsrc/pkgsrc/biology/
CVS/                      fastx-toolkit/            openbabel/
Makefile                  filter-fastq/             p5-Bio-ASN1-EntrezGene/
R-popbio/                 fluctuate/                pdbalign/
ad2vcf/                   gabedit/                  peak-classifier/
arka/                     generand/                 phylip/
azara/                    genesplicer/              plink/
bcftools/                 glimmer/                  plinkseq/
beagle/                   gnome-chemistry-utils/    primer3/
bedtools/                 gp/                       profit/
biolibc/                  gromacs/                  puzzle/
biolibc-tools/            hisat2/                   py-biopython/
bioperl/                  hmmer/                    py-cutadapt/
bodr/                     htslib/                   py-dnaio/
bowtie2/                  igv/                      py-pydicom/
bwa/                      kallisto/                 racon/
canu/                     lucy/                     rasmol/
cdhit/                    maeparser/                samtools/
chemical-mime-data/       miniasm/                  sewer/
chemtool/                 minimap2/                 stacks/
clustalw/                 molsketch/                stride/
coalesce/                 mopac/                    trimmomatic/
coordgenlibs/             mpqc/                     vcf-split/
fastDNAml/                mummer/                   vcf2hap/
fastp/                    ncbi-blast+/              vsearch/
fastqc/                   nut/                      xylem/
```

**Comment by xiaoyaohao** [comment]
Hello, Jason

Yes, I just want to run it, but I don't have root access.
I downloaded pkgsrc from HTTP, then 
`~/pkgsrc/biology/vcf-split`
`~/linux3-x86_64/bin/bmake install clean`
 However, I got the error:
`sh: /usr/pkg/sbin/pkg_info: No such file or directory`
I think maybe the problem is that I don't have the root access?

Thanks,
Jiahao

**Comment by outpaddling** [comment]
Hello Jianhao,

No, you do not need root access / admin rights, as stated in the README.

Please see the instructions under "Installing via pkgsrc" at [https://github.com/auerlab/vcf-split](https://github.com/auerlab/vcf-split).  I think if you follow these instructions carefully, you won't encounter the errors you reported.  If you run into any trouble, please provide the exact commands you ran.  I'm not sure what you mean by "downloaded pkgsrc from HTTP" or "~/pkgsrc/biology/vcf-split".

Cheers,

    Jason

**Comment by xiaoyaohao** [comment]
Hello, Jason,
I'm sorry for not expressing clearly, I will try to install via pkgsrc.
Thank, 
Jiahao

**Comment by outpaddling** [comment]
Any luck?  If you run into any trouble with auto-pkgsrc-setup or installing packages afterward, let me know and I'll try to improve the instructions.

**Comment by xiaoyaohao** [comment]
Thanks, the auto-pkgsrc-setup works, it's wonderful.
Jiahao

**Comment by outpaddling** [comment]
Good to hear.  Enjoy...
